---
version: 2
project_name: Tasky
builds:
  - main: ./cli/tasky/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

release:
  mode: keep-existing
  
  github:
    owner: shahriaarrr
    name: Tasky
